config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'vendors#index'
  # resources :products

  resources :vendors do
    resources :products
  end

  scope '/api' do
    resources :vendors do
      resources :products
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord

  belongs_to :vendor
  has_many_attached :uploaded_files

  validates :name, :vendor_id, :price, :quantity, presence: true
  validates_numericality_of :quantity, greater_than: 0
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/vendor.rb
class Vendor < ApplicationRecord
  validates :name, presence: true

  validates :name, :phone, uniqueness: true

  validates :phone, format: {
    with: /\A(?:\+?\d{1,3}\s*-?)?\(?(?:\d{3})?\)?[- ]?\d{3}[- ]?\d{4}\z/,
    message: 'Wrong phone format'
  }

  has_many :products, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    sign_in_url = new_user_session_url
    if request.referer == sign_in_url
      super
    else
      stored_location_for(resource) || request.referer || vendors_path
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :set_vendor

  # GET /products
  def index
    @products = @vendor.products.all.includes(:vendor)
    render json: @products if request.env['PATH_INFO'].split('/')[1] == "api"
  end

  # GET /products/1
  def show
    render json: @product if request.env['PATH_INFO'].split('/')[1] == "api"
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to vendor_product_path(vendor_id: @vendor.id, id: @product.id), notice: 'Product was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /products/1
  def update
    if @product.update(product_params)
      redirect_to vendor_product_path(vendor_id: @product.vendor_id, id: @product.id),
                                      notice: 'Product was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /products/1
  def destroy
    @product.destroy
    redirect_to vendor_products_path(vendor_id: params[:vendor_id]), notice: 'Product was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    def set_vendor
      @vendor = Vendor.find(params[:vendor_id]) if params[:vendor_id].present?
    end

    # Only allow a trusted parameter "white list" through.
    def product_params
      if params[:product][:vendor_id].blank?
        params[:product][:vendor_id] = params[:vendor_id]
      end
      params.require(:product).permit(:name, :vendor_id, :price, :quantity, uploaded_files: []  )
    end
end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
  before_action :authenticate_user!

  before_action :set_vendor, only: [:show, :edit, :update, :destroy]

  # GET /vendors
  def index
    @vendors = Vendor.all.includes(:products)
    render json: @vendors if request.env['PATH_INFO'].split('/')[1] == "api"
  end

  # GET /vendors/1
  def show
    render json: @vendor if request.env['PATH_INFO'].split('/')[1] == "api"
  end

  # GET /vendors/new
  def new
    @vendor = Vendor.new
  end

  # GET /vendors/1/edit
  def edit
  end

  # POST /vendors
  def create
    @vendor = Vendor.new(vendor_params)

    if @vendor.save
      redirect_to @vendor, notice: 'Vendor was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /vendors/1
  def update
    if @vendor.update(vendor_params)
      redirect_to @vendor, notice: 'Vendor was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /vendors/1
  def destroy
    @vendor.destroy
    redirect_to vendors_url, notice: 'Vendor was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vendor
      begin
        @vendor = Vendor.find(params[:id])
      rescue => e
        render json: e, status: :unprocessable_entity
      end
    end

    # Only allow a trusted parameter "white list" through.
    def vendor_params
      params.require(:vendor).permit(:name, :phone)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body class="row" style="width: 60%; margin: 100px auto;">

    <%= yield %>

  </body>
</html>

app/views/products/_form.html.erb
<%= form_with(url: url,model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <strong>Vendor:</strong>
    <%= @vendor&.name %>
  </p>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity %>
  </div>

  <div class="field">
    <%= form.label :uploaded_file %>
    <%= form.file_field :uploaded_files, multiple: true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product , url: vendor_product_path(vendor_id: @product.vendor_id, id: @product.id) %>

<%= link_to 'Show', vendor_product_path(vendor_id: @product.vendor_id, id: @product.id) %> |
<%= link_to 'Back', vendor_products_path(vendor_id: @product.vendor_id) %>

app/views/products/index.html.erb
<p id="notice" class="alert-box success radius"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Vendor</th>
      <th>Price</th>
      <th>Quantity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.vendor&.name %></td>
        <td><%= product.price %></td>
        <td><%= product.quantity %></td>
        <td><%= link_to 'Show', vendor_product_path(vendor_id: product.vendor_id, id: product.id) %></td>
        <td><%= link_to 'Edit', edit_vendor_product_path(vendor_id: product.vendor_id, id: product.id) %></td>
        <td><%= link_to 'Destroy', vendor_product_path(vendor_id: product.vendor_id, id: product.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_vendor_product_path %> |

<%= link_to 'Back', @vendor %>

app/views/products/new.html.erb
<div>  
  <h1>New Product</h1>

  <%= render 'form', product: @product, url: vendor_products_path(vendor_id: params[:vendor_id])%>

  <%= link_to 'Back', vendor_products_path(vendor_id: params[:vendor_id]) %>
</div>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Vendor:</strong>
  <%= @product.vendor&.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @product.quantity %>
</p>

<p>
  <strong>Uploaded Files:</strong> | <strong>count: <%= @product.uploaded_files.size %> </strong>
  <% @product.uploaded_files.each do |uploaded_file| %>
  <p>
    <strong>Uploaded Files:</strong>
    <%= link_to uploaded_file.filename, uploaded_file, download:true %>
  </p>
  <% end %>
</p>

<%= link_to 'Edit', edit_vendor_product_path(vendor_id: @product.vendor_id, id: @product.id) %> |
<%= link_to 'Back', vendor_products_path(vendor_id: @product.vendor_id) %>

app/views/vendors/_form.html.erb
<%= form_with(model: vendor, local: true) do |form| %>
  <% if vendor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vendor.errors.count, "error") %> prohibited this vendor from being saved:</h2>

      <ul>
      <% vendor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/vendors/edit.html.erb
<h1>Editing Vendor</h1>

<%= render 'form', vendor: @vendor %>

<%= link_to 'Show', @vendor %> |
<%= link_to 'Back', vendors_path %>

app/views/vendors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vendors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @vendors.each do |vendor| %>
      <tr>
        <td><%= vendor.name %></td>
        <td><%= vendor.phone %></td>
        <td><%= link_to 'Products', vendor_products_path(vendor_id: vendor.id) %></td>
        <td><%= link_to 'Show', vendor %></td>
        <td><%= link_to 'Edit', edit_vendor_path(vendor) %></td>
        <td><%= link_to 'Destroy', vendor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vendor', new_vendor_path %>

app/views/vendors/new.html.erb
<h1>New Vendor</h1>

<%= render 'form', vendor: @vendor %>

<%= link_to 'Back', vendors_path %>

app/views/vendors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @vendor.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @vendor.phone %>
</p>

<p>
  <%= link_to 'Products', vendor_products_path(vendor_id: @vendor.id) %>
</p>

<%= link_to 'Edit', edit_vendor_path(@vendor) %> |
<%= link_to 'Back', vendors_path %>